[workspace]
resolver = "3"
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/moxy"
homepage = "https://www.github.com/aacebo/moxy"
repository = "https://www.github.com/aacebo/moxy"
keywords = ["macro", "framework", "proc", "rust"]
categories = ["development-tools::procedural-macro-helpers", "rust-patterns", "no-std"]
include = [
    "Cargo.toml",
    "README.md",
    "LICENSE*",
    "src/**",
    "build.rs",
]

[workspace.lints.clippy]
collapsible-if = "allow"
new-ret-no-self = "allow"
get_first = "allow"
explicit_counter_loop = "allow"
type_complexity = "allow"

[package]
name = "moxy"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
default = ["ast", "token", "fmt", "template", "diagnostic", "test"]
ast = ["moxy-ast"]
fmt = ["moxy-fmt"]
token = ["moxy-token"]
template = ["moxy-template"]
diagnostic = ["moxy-diagnostic"]
test = ["moxy-test"]
serde = ["moxy-ast/serde", "moxy-token/serde", "moxy-fmt/serde"]
proc-macro2 = ["moxy-token/proc-macro2"]

[dependencies]
moxy-ast = { path = "crates/moxy-ast", optional = true }
moxy-diagnostic = { path = "crates/moxy-diagnostic", optional = true }
moxy-fmt = { path = "crates/moxy-fmt", optional = true }
moxy-token = { path = "crates/moxy-token", optional = true }
moxy-template = { path = "crates/moxy-template", optional = true }
moxy-test = { path = "crates/moxy-test", optional = true }
