[workspace]
resolver = "3"
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/moxy"
homepage = "https://www.github.com/aacebo/moxy"
repository = "https://www.github.com/aacebo/moxy"
keywords = ["macro", "framework", "proc", "rust"]
categories = ["development-tools::procedural-macro-helpers", "rust-patterns", "no-std"]
include = [
    "Cargo.toml",
    "README.md",
    "LICENSE*",
    "src/**",
    "build.rs",
]

[workspace.lints.clippy]
collapsible_if = "allow"
new_ret_no_self = "allow"
get_first = "allow"
explicit_counter_loop = "allow"
type_complexity = "allow"
large_enum_variant = "allow"

[workspace.dependencies]
moxy = { path = ".", version = "0.1.0" }
moxy-ast = { path = "crates/moxy-ast", version = "0.1.0" }
moxy-build = { path = "crates/moxy-build", version = "0.1.0" }
moxy-derive = { path = "crates/moxy-derive", version = "0.1.0" }
moxy-diagnostic = { path = "crates/moxy-diagnostic", version = "0.1.0" }
moxy-fmt = { path = "crates/moxy-fmt", version = "0.1.0" }
moxy-token = { path = "crates/moxy-token", version = "0.1.0" }
moxy-template = { path = "crates/moxy-template", version = "0.1.0" }

serde = { version = "1", features = ["derive"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
trybuild = { version = "1" }

[package]
name = "moxy"
description = "A modular Rust syntax toolkit for tokenization, parsing, formatting, diagnostics, and quasi-quoting."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--generate-link-to-definition",
    "--generate-macro-expansion"
]

[lib]
doctest = false

[lints]
workspace = true

[features]
default = ["ast", "token"]
full = ["ast", "token", "build", "fmt", "template", "derive", "diagnostic", "serde", "proc-macro2"]
ast = ["dep:moxy-ast", "token"]
build = ["dep:moxy-build"]
fmt = ["dep:moxy-fmt", "ast"]
token = ["dep:moxy-token"]
template = ["dep:moxy-template", "token"]
derive = ["dep:moxy-derive", "ast", "diagnostic", "fmt", "template"]
diagnostic = ["dep:moxy-diagnostic", "token"]
serde = ["ast", "fmt", "token", "moxy-ast/serde", "moxy-token/serde", "moxy-fmt/serde"]
proc-macro2 = ["token", "moxy-token/proc-macro2"]

[dependencies]
moxy-ast = { workspace = true, optional = true }
moxy-build = { workspace = true, optional = true }
moxy-derive = { workspace = true, optional = true }
moxy-diagnostic = { workspace = true, optional = true }
moxy-fmt = { workspace = true, optional = true }
moxy-token = { workspace = true, optional = true }
moxy-template = { workspace = true, optional = true }

[dev-dependencies]
serde.workspace = true
proc-macro2.workspace = true
trybuild.workspace = true
serde_json = "1"
