[package]
name = "moxy-test"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
default = ["macros"]
macros = ["moxy-test-macros"]

[dependencies]
moxy-test-macros = { path = "macros", optional = true }
