//! AST traversal: the [`Visit`] (read-only) and [`VisitMut`] (in-place) traits,
//! plus the free `walk_*` functions their default methods delegate to.
//!
//! Each node type has one `visit_*` method whose default body walks into the
//! node's children. Override a method to inspect (or, for `VisitMut`, rewrite) a
//! node; call the matching `walk_*` to continue descending, or skip it to prune
//! that subtree. This mirrors the model `syn` uses.
//!
//! The bulk of the trait methods and walkers are generated by [`define_visit!`]
//! from a node->children spec; a handful of irregularly-shaped nodes (private
//! fields, tuple variants, `Option<tuple>` payloads) have hand-written walkers
//! below the macro invocation.

#[macro_use]
mod macros;

use crate::args::*;
use crate::attr::meta::*;
use crate::attr::*;
use crate::expr::*;
use crate::fields::*;
use crate::generics::*;
use crate::item::*;
use crate::member::*;
use crate::misc::*;
use crate::pat::*;
use crate::path::PathArguments;
use crate::sig::*;
use crate::stmt::*;
use crate::ty::*;
use crate::use_tree::*;
use crate::vis::*;
use crate::{Delimited, MacroCall, Path, PathSegment, ReturnType, Variant};

/// `ItemMod::content` is `Option<Delimited<Vec<Item>>>`; the inner delimited
/// item list gets its own visitor so the macro field can reference it by name.
type ItemModContent = Delimited<Vec<Item>>;

define_visit! {
    // ===== expressions ===================================================
    enum Expr {
        visit: visit_expr, visit_mut: visit_expr_mut,
        walk: walk_expr, walk_mut: walk_expr_mut,
        variants {
            Unary(visit_unary_expr / visit_unary_expr_mut),
            Binary(visit_binary_expr / visit_binary_expr_mut),
            Postfix(visit_postfix_expr / visit_postfix_expr_mut),
            Block(visit_block_expr / visit_block_expr_mut),
            Jump(visit_jump_expr / visit_jump_expr_mut),
            Primary(visit_primary_expr / visit_primary_expr_mut),
            Infer,
            Verbatim(skip),
        }
    }

    enum UnaryExpr {
        visit: visit_unary_expr, visit_mut: visit_unary_expr_mut,
        walk: walk_unary_expr, walk_mut: walk_unary_expr_mut,
        variants {
            Reference(visit_expr_reference / visit_expr_reference_mut),
            Unary(visit_expr_unary / visit_expr_unary_mut),
            Cast(visit_expr_cast / visit_expr_cast_mut),
            Try(visit_expr_try / visit_expr_try_mut),
        }
    }

    enum BinaryExpr {
        visit: visit_binary_expr, visit_mut: visit_binary_expr_mut,
        walk: walk_binary_expr, walk_mut: walk_binary_expr_mut,
        variants {
            Binary(visit_expr_binary / visit_expr_binary_mut),
            Assign(visit_expr_assign / visit_expr_assign_mut),
            AssignOp(visit_expr_assign_op / visit_expr_assign_op_mut),
            Range(visit_expr_range / visit_expr_range_mut),
            Type(visit_expr_type / visit_expr_type_mut),
        }
    }

    enum PostfixExpr {
        visit: visit_postfix_expr, visit_mut: visit_postfix_expr_mut,
        walk: walk_postfix_expr, walk_mut: walk_postfix_expr_mut,
        variants {
            Call(visit_expr_call / visit_expr_call_mut),
            MethodCall(visit_expr_method_call / visit_expr_method_call_mut),
            Field(visit_expr_field / visit_expr_field_mut),
            Index(visit_expr_index / visit_expr_index_mut),
            Await(visit_expr_await / visit_expr_await_mut),
        }
    }

    enum BlockExpr {
        visit: visit_block_expr, visit_mut: visit_block_expr_mut,
        walk: walk_block_expr, walk_mut: walk_block_expr_mut,
        variants {
            Brace(visit_expr_brace / visit_expr_brace_mut),
            If(visit_expr_if / visit_expr_if_mut),
            While(visit_expr_while / visit_expr_while_mut),
            ForLoop(visit_expr_for_loop / visit_expr_for_loop_mut),
            Loop(visit_expr_loop / visit_expr_loop_mut),
            Match(visit_expr_match / visit_expr_match_mut),
            Async(visit_expr_async / visit_expr_async_mut),
            Unsafe(visit_expr_unsafe / visit_expr_unsafe_mut),
            Const(visit_expr_const / visit_expr_const_mut),
            TryBlock(visit_expr_try_block / visit_expr_try_block_mut),
        }
    }

    enum JumpExpr {
        visit: visit_jump_expr, visit_mut: visit_jump_expr_mut,
        walk: walk_jump_expr, walk_mut: walk_jump_expr_mut,
        variants {
            Return(visit_expr_return / visit_expr_return_mut),
            Break(visit_expr_break / visit_expr_break_mut),
            Continue(visit_expr_continue / visit_expr_continue_mut),
            Yield(visit_expr_yield / visit_expr_yield_mut),
        }
    }

    enum PrimaryExpr {
        visit: visit_primary_expr, visit_mut: visit_primary_expr_mut,
        walk: walk_primary_expr, walk_mut: walk_primary_expr_mut,
        variants {
            Lit(visit_expr_lit / visit_expr_lit_mut),
            Path(visit_expr_path / visit_expr_path_mut),
            Struct(visit_expr_struct / visit_expr_struct_mut),
            Closure(visit_expr_closure / visit_expr_closure_mut),
            Tuple(visit_expr_tuple / visit_expr_tuple_mut),
            Array(visit_expr_array / visit_expr_array_mut),
            Repeat(visit_expr_repeat / visit_expr_repeat_mut),
            Let(visit_expr_let / visit_expr_let_mut),
            Paren(visit_expr_paren / visit_expr_paren_mut),
            Group(visit_expr_group / visit_expr_group_mut),
            Macro(visit_expr_macro / visit_expr_macro_mut),
        }
    }

    // -- unary --
    struct ExprReference {
        visit: visit_expr_reference, visit_mut: visit_expr_reference_mut,
        walk: walk_expr_reference, walk_mut: walk_expr_reference_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            and_punct: skip,
            mutability: leaf,
            expr: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprUnary {
        visit: visit_expr_unary, visit_mut: visit_expr_unary_mut,
        walk: walk_expr_unary, walk_mut: walk_expr_unary_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            op: leaf,
            expr: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprCast {
        visit: visit_expr_cast, visit_mut: visit_expr_cast_mut,
        walk: walk_expr_cast, walk_mut: walk_expr_cast_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            expr: box => visit_expr / visit_expr_mut,
            as_keyword: skip,
            ty: box => visit_type / visit_type_mut,
        }
    }
    struct ExprTry {
        visit: visit_expr_try, visit_mut: visit_expr_try_mut,
        walk: walk_expr_try, walk_mut: walk_expr_try_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            expr: box => visit_expr / visit_expr_mut,
            question_punct: skip,
        }
    }

    // -- binary --
    struct ExprBinary {
        visit: visit_expr_binary, visit_mut: visit_expr_binary_mut,
        walk: walk_expr_binary, walk_mut: walk_expr_binary_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            left: box => visit_expr / visit_expr_mut,
            op: leaf,
            right: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprAssign {
        visit: visit_expr_assign, visit_mut: visit_expr_assign_mut,
        walk: walk_expr_assign, walk_mut: walk_expr_assign_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            left: box => visit_expr / visit_expr_mut,
            eq: skip,
            right: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprAssignOp {
        visit: visit_expr_assign_op, visit_mut: visit_expr_assign_op_mut,
        walk: walk_expr_assign_op, walk_mut: walk_expr_assign_op_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            left: box => visit_expr / visit_expr_mut,
            op: leaf,
            right: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprRange {
        visit: visit_expr_range, visit_mut: visit_expr_range_mut,
        walk: walk_expr_range, walk_mut: walk_expr_range_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            start: opt_box => visit_expr / visit_expr_mut,
            limits: leaf,
            end: opt_box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprType {
        visit: visit_expr_type, visit_mut: visit_expr_type_mut,
        walk: walk_expr_type, walk_mut: walk_expr_type_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            expr: box => visit_expr / visit_expr_mut,
            colon_punct: skip,
            ty: box => visit_type / visit_type_mut,
        }
    }

    // -- postfix --
    struct ExprCall {
        visit: visit_expr_call, visit_mut: visit_expr_call_mut,
        walk: walk_expr_call, walk_mut: walk_expr_call_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            func: box => visit_expr / visit_expr_mut,
            args: seq_punct => visit_expr / visit_expr_mut,
        }
    }
    struct ExprMethodCall {
        visit: visit_expr_method_call, visit_mut: visit_expr_method_call_mut,
        walk: walk_expr_method_call, walk_mut: walk_expr_method_call_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            receiver: box => visit_expr / visit_expr_mut,
            dot: skip,
            method: skip,
            turbofish: opt => visit_angle_arguments / visit_angle_arguments_mut,
            args: seq_punct => visit_expr / visit_expr_mut,
        }
    }
    struct ExprField {
        visit: visit_expr_field, visit_mut: visit_expr_field_mut,
        walk: walk_expr_field, walk_mut: walk_expr_field_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            base: box => visit_expr / visit_expr_mut,
            dot: skip,
            member: skip,
        }
    }
    struct ExprIndex {
        visit: visit_expr_index, visit_mut: visit_expr_index_mut,
        walk: walk_expr_index, walk_mut: walk_expr_index_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            base: box => visit_expr / visit_expr_mut,
            index: delim => visit_expr / visit_expr_mut,
        }
    }
    struct ExprAwait {
        visit: visit_expr_await, visit_mut: visit_expr_await_mut,
        walk: walk_expr_await, walk_mut: walk_expr_await_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            base: box => visit_expr / visit_expr_mut,
            dot: skip,
            await_keyword: skip,
        }
    }

    // -- block --
    struct ExprBrace {
        visit: visit_expr_brace, visit_mut: visit_expr_brace_mut,
        walk: walk_expr_brace, walk_mut: walk_expr_brace_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            label: skip,
            block => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprIf {
        visit: visit_expr_if, visit_mut: visit_expr_if_mut,
        walk: walk_expr_if, walk_mut: walk_expr_if_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            if_keyword: skip,
            cond: box => visit_expr / visit_expr_mut,
            then_branch => visit_stmt_block / visit_stmt_block_mut,
            else_keyword: skip,
            else_branch: opt_box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprWhile {
        visit: visit_expr_while, visit_mut: visit_expr_while_mut,
        walk: walk_expr_while, walk_mut: walk_expr_while_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            label: skip,
            while_keyword: skip,
            cond: box => visit_expr / visit_expr_mut,
            body => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprForLoop {
        visit: visit_expr_for_loop, visit_mut: visit_expr_for_loop_mut,
        walk: walk_expr_for_loop, walk_mut: walk_expr_for_loop_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            label: skip,
            for_keyword: skip,
            pat: box => visit_pattern / visit_pattern_mut,
            in_keyword: skip,
            expr: box => visit_expr / visit_expr_mut,
            body => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprLoop {
        visit: visit_expr_loop, visit_mut: visit_expr_loop_mut,
        walk: walk_expr_loop, walk_mut: walk_expr_loop_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            label: skip,
            loop_keyword: skip,
            body => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprMatch {
        visit: visit_expr_match, visit_mut: visit_expr_match_mut,
        walk: walk_expr_match, walk_mut: walk_expr_match_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            match_keyword: skip,
            expr: box => visit_expr / visit_expr_mut,
            arms: seq => visit_match_arm / visit_match_arm_mut,
        }
    }
    struct MatchArm {
        visit: visit_match_arm, visit_mut: visit_match_arm_mut,
        walk: walk_match_arm, walk_mut: walk_match_arm_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            pat => visit_pattern / visit_pattern_mut,
            if_keyword: skip,
            guard: opt_box => visit_expr / visit_expr_mut,
            fat_arrow: skip,
            body => visit_expr / visit_expr_mut,
            comma: skip,
        }
    }
    struct ExprAsync {
        visit: visit_expr_async, visit_mut: visit_expr_async_mut,
        walk: walk_expr_async, walk_mut: walk_expr_async_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            async_keyword: skip,
            move_keyword: skip,
            block => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprUnsafe {
        visit: visit_expr_unsafe, visit_mut: visit_expr_unsafe_mut,
        walk: walk_expr_unsafe, walk_mut: walk_expr_unsafe_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            unsafe_keyword: skip,
            block => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprConst {
        visit: visit_expr_const, visit_mut: visit_expr_const_mut,
        walk: walk_expr_const, walk_mut: walk_expr_const_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            const_keyword: skip,
            block => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ExprTryBlock {
        visit: visit_expr_try_block, visit_mut: visit_expr_try_block_mut,
        walk: walk_expr_try_block, walk_mut: walk_expr_try_block_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            try_keyword: skip,
            block => visit_stmt_block / visit_stmt_block_mut,
        }
    }

    // -- jump --
    struct ExprReturn {
        visit: visit_expr_return, visit_mut: visit_expr_return_mut,
        walk: walk_expr_return, walk_mut: walk_expr_return_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            return_keyword: skip,
            expr: opt_box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprBreak {
        visit: visit_expr_break, visit_mut: visit_expr_break_mut,
        walk: walk_expr_break, walk_mut: walk_expr_break_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            break_keyword: skip,
            label: skip,
            expr: opt_box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprContinue {
        visit: visit_expr_continue, visit_mut: visit_expr_continue_mut,
        walk: walk_expr_continue, walk_mut: walk_expr_continue_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            continue_keyword: skip,
            label: skip,
        }
    }
    struct ExprYield {
        visit: visit_expr_yield, visit_mut: visit_expr_yield_mut,
        walk: walk_expr_yield, walk_mut: walk_expr_yield_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            yield_keyword: skip,
            expr: opt_box => visit_expr / visit_expr_mut,
        }
    }

    // -- primary --
    struct ExprLit {
        visit: visit_expr_lit, visit_mut: visit_expr_lit_mut,
        walk: walk_expr_lit, walk_mut: walk_expr_lit_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            lit: skip,
        }
    }
    struct ExprPath {
        visit: visit_expr_path, visit_mut: visit_expr_path_mut,
        walk: walk_expr_path, walk_mut: walk_expr_path_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            qself: opt => visit_qself / visit_qself_mut,
            path => visit_path / visit_path_mut,
        }
    }
    struct ExprStruct {
        visit: visit_expr_struct, visit_mut: visit_expr_struct_mut,
        walk: walk_expr_struct, walk_mut: walk_expr_struct_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            qself: opt => visit_qself / visit_qself_mut,
            path => visit_path / visit_path_mut,
            body: delim => visit_struct_body / visit_struct_body_mut,
        }
    }
    struct ExprClosure {
        visit: visit_expr_closure, visit_mut: visit_expr_closure_mut,
        walk: walk_expr_closure, walk_mut: walk_expr_closure_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            lifetimes: opt => visit_bound_lifetimes / visit_bound_lifetimes_mut,
            constness: leaf,
            movability: leaf,
            asyncness: leaf,
            capture: skip,
            pipes: skip,
            inputs: punct => visit_closure_param / visit_closure_param_mut,
            output => visit_return_type / visit_return_type_mut,
            body: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprTuple {
        visit: visit_expr_tuple, visit_mut: visit_expr_tuple_mut,
        walk: walk_expr_tuple, walk_mut: walk_expr_tuple_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            elems: seq_punct => visit_expr / visit_expr_mut,
        }
    }
    struct ExprArray {
        visit: visit_expr_array, visit_mut: visit_expr_array_mut,
        walk: walk_expr_array, walk_mut: walk_expr_array_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            elems: seq_punct => visit_expr / visit_expr_mut,
        }
    }
    struct ExprRepeat {
        visit: visit_expr_repeat, visit_mut: visit_expr_repeat_mut,
        walk: walk_expr_repeat, walk_mut: walk_expr_repeat_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            content: delim => visit_repeat_inner / visit_repeat_inner_mut,
        }
    }
    struct RepeatInner {
        visit: visit_repeat_inner, visit_mut: visit_repeat_inner_mut,
        walk: walk_repeat_inner, walk_mut: walk_repeat_inner_mut,
        fields {
            elem: box => visit_expr / visit_expr_mut,
            semi: skip,
            len: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprLet {
        visit: visit_expr_let, visit_mut: visit_expr_let_mut,
        walk: walk_expr_let, walk_mut: walk_expr_let_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            let_keyword: skip,
            pat: box => visit_pattern / visit_pattern_mut,
            eq: skip,
            expr: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprParen {
        visit: visit_expr_paren, visit_mut: visit_expr_paren_mut,
        walk: walk_expr_paren, walk_mut: walk_expr_paren_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            content: delim => visit_expr / visit_expr_mut,
        }
    }
    struct ExprGroup {
        visit: visit_expr_group, visit_mut: visit_expr_group_mut,
        walk: walk_expr_group, walk_mut: walk_expr_group_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            expr: box => visit_expr / visit_expr_mut,
        }
    }
    struct ExprMacro {
        visit: visit_expr_macro, visit_mut: visit_expr_macro_mut,
        walk: walk_expr_macro, walk_mut: walk_expr_macro_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            mac => visit_macro_call / visit_macro_call_mut,
        }
    }
    struct StructBody {
        visit: visit_struct_body, visit_mut: visit_struct_body_mut,
        walk: walk_struct_body, walk_mut: walk_struct_body_mut,
        fields {
            fields: punct => visit_field_value / visit_field_value_mut,
            rest: opt_pair => visit_expr / visit_expr_mut,
        }
    }

    // ===== statements ====================================================
    struct StmtBlock {
        visit: visit_stmt_block, visit_mut: visit_stmt_block_mut,
        walk: walk_stmt_block, walk_mut: walk_stmt_block_mut,
        fields {
            stmts: seq => visit_stmt / visit_stmt_mut,
        }
    }
    struct StmtLocal {
        visit: visit_stmt_local, visit_mut: visit_stmt_local_mut,
        walk: walk_stmt_local, walk_mut: walk_stmt_local_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            let_keyword: skip,
            pat => visit_pattern / visit_pattern_mut,
            ty: opt_pair => visit_type / visit_type_mut,
            init: opt => visit_stmt_local_init / visit_stmt_local_init_mut,
            semi: skip,
        }
    }
    struct StmtLocalInit {
        visit: visit_stmt_local_init, visit_mut: visit_stmt_local_init_mut,
        walk: walk_stmt_local_init, walk_mut: walk_stmt_local_init_mut,
        fields {
            eq: skip,
            expr => visit_expr / visit_expr_mut,
            diverge: opt_pair => visit_expr / visit_expr_mut,
        }
    }
    struct StmtMacro {
        visit: visit_stmt_macro, visit_mut: visit_stmt_macro_mut,
        walk: walk_stmt_macro, walk_mut: walk_stmt_macro_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            mac => visit_macro_call / visit_macro_call_mut,
            semi: skip,
        }
    }

    // ===== patterns ======================================================
    enum Pattern {
        visit: visit_pattern, visit_mut: visit_pattern_mut,
        walk: walk_pattern, walk_mut: walk_pattern_mut,
        variants {
            Wild,
            Rest,
            Ident(visit_pat_ident / visit_pat_ident_mut),
            Path(visit_pat_path / visit_pat_path_mut),
            Tuple(visit_pat_tuple / visit_pat_tuple_mut),
            TupleStruct(visit_pat_tuple_struct / visit_pat_tuple_struct_mut),
            Struct(visit_pat_struct / visit_pat_struct_mut),
            Slice(visit_pat_slice / visit_pat_slice_mut),
            Reference(visit_pat_reference / visit_pat_reference_mut),
            Or(visit_pat_or / visit_pat_or_mut),
            Lit(visit_pat_lit / visit_pat_lit_mut),
            Range(visit_pat_range / visit_pat_range_mut),
            Macro(visit_macro_call / visit_macro_call_mut),
            Type(visit_pat_type / visit_pat_type_mut),
            Group(visit_pat_group / visit_pat_group_mut),
            Paren(visit_pat_paren / visit_pat_paren_mut),
            Box(visit_pattern / visit_pattern_mut),
            Const(visit_stmt_block / visit_stmt_block_mut),
        }
    }
    struct PatIdent {
        visit: visit_pat_ident, visit_mut: visit_pat_ident_mut,
        walk: walk_pat_ident, walk_mut: walk_pat_ident_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            by_ref: skip,
            mutability: leaf,
            ident: skip,
            subpat: opt_pair => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatPath {
        visit: visit_pat_path, visit_mut: visit_pat_path_mut,
        walk: walk_pat_path, walk_mut: walk_pat_path_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            qself: opt => visit_qself / visit_qself_mut,
            path => visit_path / visit_path_mut,
        }
    }
    struct PatTuple {
        visit: visit_pat_tuple, visit_mut: visit_pat_tuple_mut,
        walk: walk_pat_tuple, walk_mut: walk_pat_tuple_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            elems: seq_punct => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatTupleStruct {
        visit: visit_pat_tuple_struct, visit_mut: visit_pat_tuple_struct_mut,
        walk: walk_pat_tuple_struct, walk_mut: walk_pat_tuple_struct_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            qself: opt => visit_qself / visit_qself_mut,
            path => visit_path / visit_path_mut,
            elems: seq_punct => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatStruct {
        visit: visit_pat_struct, visit_mut: visit_pat_struct_mut,
        walk: walk_pat_struct, walk_mut: walk_pat_struct_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            qself: opt => visit_qself / visit_qself_mut,
            path => visit_path / visit_path_mut,
            body: delim => visit_pat_struct_body / visit_pat_struct_body_mut,
        }
    }
    struct PatStructBody {
        visit: visit_pat_struct_body, visit_mut: visit_pat_struct_body_mut,
        walk: walk_pat_struct_body, walk_mut: walk_pat_struct_body_mut,
        fields {
            fields: punct => visit_pat_field / visit_pat_field_mut,
            rest: skip,
        }
    }
    struct PatField {
        visit: visit_pat_field, visit_mut: visit_pat_field_mut,
        walk: walk_pat_field, walk_mut: walk_pat_field_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            member: skip,
            colon: skip,
            pat => visit_pattern / visit_pattern_mut,
            shorthand: skip,
        }
    }
    struct PatSlice {
        visit: visit_pat_slice, visit_mut: visit_pat_slice_mut,
        walk: walk_pat_slice, walk_mut: walk_pat_slice_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            elems: seq_punct => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatReference {
        visit: visit_pat_reference, visit_mut: visit_pat_reference_mut,
        walk: walk_pat_reference, walk_mut: walk_pat_reference_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            and: skip,
            mutability: leaf,
            pat: box => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatOr {
        visit: visit_pat_or, visit_mut: visit_pat_or_mut,
        walk: walk_pat_or, walk_mut: walk_pat_or_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            cases: punct => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatLit {
        visit: visit_pat_lit, visit_mut: visit_pat_lit_mut,
        walk: walk_pat_lit, walk_mut: walk_pat_lit_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            expr => visit_expr / visit_expr_mut,
        }
    }
    struct PatRange {
        visit: visit_pat_range, visit_mut: visit_pat_range_mut,
        walk: walk_pat_range, walk_mut: walk_pat_range_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            start: opt => visit_expr / visit_expr_mut,
            limits: leaf,
            end: opt => visit_expr / visit_expr_mut,
        }
    }
    struct PatType {
        visit: visit_pat_type, visit_mut: visit_pat_type_mut,
        walk: walk_pat_type, walk_mut: walk_pat_type_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            pat: box => visit_pattern / visit_pattern_mut,
            colon: skip,
            ty: box => visit_type / visit_type_mut,
        }
    }
    struct PatGroup {
        visit: visit_pat_group, visit_mut: visit_pat_group_mut,
        walk: walk_pat_group, walk_mut: walk_pat_group_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            pat: box => visit_pattern / visit_pattern_mut,
        }
    }
    struct PatParen {
        visit: visit_pat_paren, visit_mut: visit_pat_paren_mut,
        walk: walk_pat_paren, walk_mut: walk_pat_paren_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            content: delim => visit_pattern / visit_pattern_mut,
        }
    }

    // ===== types =========================================================
    enum Type {
        visit: visit_type, visit_mut: visit_type_mut,
        walk: walk_type, walk_mut: walk_type_mut,
        variants {
            Never(skip),
            Infer(skip),
            Path(visit_type_path / visit_type_path_mut),
            Tuple(visit_type_tuple / visit_type_tuple_mut),
            Array(visit_type_array / visit_type_array_mut),
            Slice(visit_type_slice / visit_type_slice_mut),
            Reference(visit_type_reference / visit_type_reference_mut),
            Pointer(visit_type_pointer / visit_type_pointer_mut),
            BareFn(visit_type_bare_fn / visit_type_bare_fn_mut),
            ImplTrait(visit_type_impl_trait / visit_type_impl_trait_mut),
            TraitObject(visit_type_trait_object / visit_type_trait_object_mut),
            Paren(visit_type_paren / visit_type_paren_mut),
            Group(visit_type_group / visit_type_group_mut),
            Macro(visit_type_macro / visit_type_macro_mut),
        }
    }
    struct QSelf {
        visit: visit_qself, visit_mut: visit_qself_mut,
        walk: walk_qself, walk_mut: walk_qself_mut,
        fields {
            lt: skip,
            ty: box => visit_type / visit_type_mut,
            as_keyword: skip,
            position: skip,
        }
    }
    struct TypePath {
        visit: visit_type_path, visit_mut: visit_type_path_mut,
        walk: walk_type_path, walk_mut: walk_type_path_mut,
        fields {
            qself: opt => visit_qself / visit_qself_mut,
            path => visit_path / visit_path_mut,
        }
    }
    struct TypeTuple {
        visit: visit_type_tuple, visit_mut: visit_type_tuple_mut,
        walk: walk_type_tuple, walk_mut: walk_type_tuple_mut,
        fields {
            elems: seq_punct => visit_type / visit_type_mut,
        }
    }
    struct TypeArray {
        visit: visit_type_array, visit_mut: visit_type_array_mut,
        walk: walk_type_array, walk_mut: walk_type_array_mut,
        fields {
            content: delim => visit_array_inner / visit_array_inner_mut,
        }
    }
    struct ArrayInner {
        visit: visit_array_inner, visit_mut: visit_array_inner_mut,
        walk: walk_array_inner, walk_mut: walk_array_inner_mut,
        fields {
            elem: box => visit_type / visit_type_mut,
            semi: skip,
            len => visit_expr / visit_expr_mut,
        }
    }
    struct TypeSlice {
        visit: visit_type_slice, visit_mut: visit_type_slice_mut,
        walk: walk_type_slice, walk_mut: walk_type_slice_mut,
        fields {
            elem: delim => visit_type / visit_type_mut,
        }
    }
    struct TypeReference {
        visit: visit_type_reference, visit_mut: visit_type_reference_mut,
        walk: walk_type_reference, walk_mut: walk_type_reference_mut,
        fields {
            and: skip,
            lifetime: skip,
            mutability: leaf,
            elem: box => visit_type / visit_type_mut,
        }
    }
    struct TypePointer {
        visit: visit_type_pointer, visit_mut: visit_type_pointer_mut,
        walk: walk_type_pointer, walk_mut: walk_type_pointer_mut,
        fields {
            star: skip,
            mutability: skip,
            elem: box => visit_type / visit_type_mut,
        }
    }
    struct TypeBareFn {
        visit: visit_type_bare_fn, visit_mut: visit_type_bare_fn_mut,
        walk: walk_type_bare_fn, walk_mut: walk_type_bare_fn_mut,
        fields {
            lifetimes: opt => visit_bound_lifetimes / visit_bound_lifetimes_mut,
            unsafety: leaf,
            abi: skip,
            fn_keyword: skip,
            params: delim => visit_bare_fn_params / visit_bare_fn_params_mut,
            output => visit_return_type / visit_return_type_mut,
        }
    }
    struct BareFnParams {
        visit: visit_bare_fn_params, visit_mut: visit_bare_fn_params_mut,
        walk: walk_bare_fn_params, walk_mut: walk_bare_fn_params_mut,
        fields {
            inputs: punct => visit_bare_fn_arg / visit_bare_fn_arg_mut,
            variadic: opt => visit_variadic / visit_variadic_mut,
        }
    }
    struct TypeImplTrait {
        visit: visit_type_impl_trait, visit_mut: visit_type_impl_trait_mut,
        walk: walk_type_impl_trait, walk_mut: walk_type_impl_trait_mut,
        fields {
            impl_keyword: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
        }
    }
    struct TypeTraitObject {
        visit: visit_type_trait_object, visit_mut: visit_type_trait_object_mut,
        walk: walk_type_trait_object, walk_mut: walk_type_trait_object_mut,
        fields {
            dyn_token: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
        }
    }
    struct TypeParen {
        visit: visit_type_paren, visit_mut: visit_type_paren_mut,
        walk: walk_type_paren, walk_mut: walk_type_paren_mut,
        fields {
            content: delim => visit_type / visit_type_mut,
        }
    }
    struct TypeGroup {
        visit: visit_type_group, visit_mut: visit_type_group_mut,
        walk: walk_type_group, walk_mut: walk_type_group_mut,
        fields {
            span: skip,
            elem: box => visit_type / visit_type_mut,
        }
    }
    struct TypeMacro {
        visit: visit_type_macro, visit_mut: visit_type_macro_mut,
        walk: walk_type_macro, walk_mut: walk_type_macro_mut,
        fields {
            mac => visit_macro_call / visit_macro_call_mut,
        }
    }
    struct TypedParam {
        visit: visit_typed_param, visit_mut: visit_typed_param_mut,
        walk: walk_typed_param, walk_mut: walk_typed_param_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            pat: box => visit_pattern / visit_pattern_mut,
            colon: skip,
            ty: box => visit_type / visit_type_mut,
        }
    }

    // ===== items =========================================================
    enum Item {
        visit: visit_item, visit_mut: visit_item_mut,
        walk: walk_item, walk_mut: walk_item_mut,
        variants {
            Use(visit_item_use / visit_item_use_mut),
            ExternCrate(visit_item_extern_crate / visit_item_extern_crate_mut),
            Mod(visit_item_mod / visit_item_mod_mut),
            Fn(visit_item_fn / visit_item_fn_mut),
            Struct(visit_item_struct / visit_item_struct_mut),
            Enum(visit_item_enum / visit_item_enum_mut),
            Union(visit_item_union / visit_item_union_mut),
            Trait(visit_item_trait / visit_item_trait_mut),
            TraitAlias(visit_item_trait_alias / visit_item_trait_alias_mut),
            Impl(visit_item_impl / visit_item_impl_mut),
            TypeAlias(visit_item_type_alias / visit_item_type_alias_mut),
            Const(visit_item_const / visit_item_const_mut),
            Static(visit_item_static / visit_item_static_mut),
            Macro(visit_item_macro / visit_item_macro_mut),
            Macro2(visit_item_macro_rules / visit_item_macro_rules_mut),
            ForeignMod(visit_item_foreign_mod / visit_item_foreign_mod_mut),
        }
    }
    struct ItemUse {
        visit: visit_item_use, visit_mut: visit_item_use_mut,
        walk: walk_item_use, walk_mut: walk_item_use_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            use_keyword: skip,
            tree => visit_use_tree / visit_use_tree_mut,
            semi_punct: skip,
        }
    }
    struct ItemExternCrate {
        visit: visit_item_extern_crate, visit_mut: visit_item_extern_crate_mut,
        walk: walk_item_extern_crate, walk_mut: walk_item_extern_crate_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            extern_keyword: skip,
            crate_keyword: skip,
            ident: skip,
            as_keyword: skip,
            rename: skip,
            semi_punct: skip,
        }
    }
    struct ItemMod {
        visit: visit_item_mod, visit_mut: visit_item_mod_mut,
        walk: walk_item_mod, walk_mut: walk_item_mod_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            unsafety: leaf,
            mod_keyword: skip,
            ident: skip,
            content: opt => visit_item_mod_content / visit_item_mod_content_mut,
            semi_punct: skip,
        }
    }
    struct ItemFn {
        visit: visit_item_fn, visit_mut: visit_item_fn_mut,
        walk: walk_item_fn, walk_mut: walk_item_fn_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            defaultness: leaf,
            sig => visit_signature / visit_signature_mut,
            body => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ItemStruct {
        visit: visit_item_struct, visit_mut: visit_item_struct_mut,
        walk: walk_item_struct, walk_mut: walk_item_struct_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            struct_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            fields => visit_fields / visit_fields_mut,
            semi_punct: skip,
        }
    }
    struct ItemEnum {
        visit: visit_item_enum, visit_mut: visit_item_enum_mut,
        walk: walk_item_enum, walk_mut: walk_item_enum_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            enum_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            variants: seq_punct => visit_variant / visit_variant_mut,
        }
    }
    struct Variant {
        visit: visit_variant, visit_mut: visit_variant_mut,
        walk: walk_variant, walk_mut: walk_variant_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            ident: skip,
            fields => visit_fields / visit_fields_mut,
            eq_punct: skip,
            discriminant: opt => visit_expr / visit_expr_mut,
        }
    }
    struct ItemUnion {
        visit: visit_item_union, visit_mut: visit_item_union_mut,
        walk: walk_item_union, walk_mut: walk_item_union_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            union_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            fields => visit_fields_named / visit_fields_named_mut,
        }
    }
    struct ItemTrait {
        visit: visit_item_trait, visit_mut: visit_item_trait_mut,
        walk: walk_item_trait, walk_mut: walk_item_trait_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            unsafety: leaf,
            auto_keyword: skip,
            trait_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            colon_punct: skip,
            supertraits: punct => visit_type_bound / visit_type_bound_mut,
            items: seq => visit_trait_item / visit_trait_item_mut,
        }
    }
    struct ItemTraitAlias {
        visit: visit_item_trait_alias, visit_mut: visit_item_trait_alias_mut,
        walk: walk_item_trait_alias, walk_mut: walk_item_trait_alias_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            trait_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            eq_punct: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
            semi_punct: skip,
        }
    }
    struct ItemImpl {
        visit: visit_item_impl, visit_mut: visit_item_impl_mut,
        walk: walk_item_impl, walk_mut: walk_item_impl_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            defaultness: leaf,
            unsafety: leaf,
            impl_keyword: skip,
            generics => visit_generics / visit_generics_mut,
            for_keyword: skip,
            trait_ref: opt => visit_trait_ref / visit_trait_ref_mut,
            self_ty => visit_type / visit_type_mut,
            items: seq => visit_impl_item / visit_impl_item_mut,
        }
    }
    struct ItemTypeAlias {
        visit: visit_item_type_alias, visit_mut: visit_item_type_alias_mut,
        walk: walk_item_type_alias, walk_mut: walk_item_type_alias_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            type_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            eq_punct: skip,
            ty => visit_type / visit_type_mut,
            semi_punct: skip,
        }
    }
    struct ItemConst {
        visit: visit_item_const, visit_mut: visit_item_const_mut,
        walk: walk_item_const, walk_mut: walk_item_const_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            const_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            colon_punct: skip,
            ty => visit_type / visit_type_mut,
            eq_punct: skip,
            expr => visit_expr / visit_expr_mut,
            semi_punct: skip,
        }
    }
    struct ItemStatic {
        visit: visit_item_static, visit_mut: visit_item_static_mut,
        walk: walk_item_static, walk_mut: walk_item_static_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            static_keyword: skip,
            mutability: leaf,
            ident: skip,
            colon_punct: skip,
            ty => visit_type / visit_type_mut,
            eq_punct: skip,
            expr => visit_expr / visit_expr_mut,
            semi_punct: skip,
        }
    }
    struct ItemMacro {
        visit: visit_item_macro, visit_mut: visit_item_macro_mut,
        walk: walk_item_macro, walk_mut: walk_item_macro_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            ident: skip,
            mac => visit_macro_call / visit_macro_call_mut,
            semi: skip,
            semi_punct: skip,
        }
    }
    struct ItemMacroRules {
        visit: visit_item_macro_rules, visit_mut: visit_item_macro_rules_mut,
        walk: walk_item_macro_rules, walk_mut: walk_item_macro_rules_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            macro_rules_keyword: skip,
            not_punct: skip,
            ident: skip,
            body: skip,
        }
    }
    struct ItemForeignMod {
        visit: visit_item_foreign_mod, visit_mut: visit_item_foreign_mod_mut,
        walk: walk_item_foreign_mod, walk_mut: walk_item_foreign_mod_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            unsafety: leaf,
            abi: skip,
            items: seq => visit_foreign_item / visit_foreign_item_mut,
        }
    }

    // ===== members =======================================================
    enum ForeignItem {
        visit: visit_foreign_item, visit_mut: visit_foreign_item_mut,
        walk: walk_foreign_item, walk_mut: walk_foreign_item_mut,
        variants {
            Fn(visit_foreign_item_fn / visit_foreign_item_fn_mut),
            Static(visit_foreign_item_static / visit_foreign_item_static_mut),
            Type(visit_foreign_item_type / visit_foreign_item_type_mut),
            Macro(visit_foreign_item_macro / visit_foreign_item_macro_mut),
        }
    }
    struct ForeignItemFn {
        visit: visit_foreign_item_fn, visit_mut: visit_foreign_item_fn_mut,
        walk: walk_foreign_item_fn, walk_mut: walk_foreign_item_fn_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            sig => visit_signature / visit_signature_mut,
            semi: skip,
        }
    }
    struct ForeignItemStatic {
        visit: visit_foreign_item_static, visit_mut: visit_foreign_item_static_mut,
        walk: walk_foreign_item_static, walk_mut: walk_foreign_item_static_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            static_keyword: skip,
            mutability: leaf,
            ident: skip,
            colon: skip,
            ty => visit_type / visit_type_mut,
            semi: skip,
        }
    }
    struct ForeignItemType {
        visit: visit_foreign_item_type, visit_mut: visit_foreign_item_type_mut,
        walk: walk_foreign_item_type, walk_mut: walk_foreign_item_type_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            type_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            semi: skip,
        }
    }
    struct ForeignItemMacro {
        visit: visit_foreign_item_macro, visit_mut: visit_foreign_item_macro_mut,
        walk: walk_foreign_item_macro, walk_mut: walk_foreign_item_macro_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            mac => visit_macro_call / visit_macro_call_mut,
            semi: skip,
        }
    }
    enum ImplItem {
        visit: visit_impl_item, visit_mut: visit_impl_item_mut,
        walk: walk_impl_item, walk_mut: walk_impl_item_mut,
        variants {
            Fn(visit_impl_item_fn / visit_impl_item_fn_mut),
            Const(visit_impl_item_const / visit_impl_item_const_mut),
            Type(visit_impl_item_type / visit_impl_item_type_mut),
            Macro(visit_impl_item_macro / visit_impl_item_macro_mut),
        }
    }
    struct ImplItemFn {
        visit: visit_impl_item_fn, visit_mut: visit_impl_item_fn_mut,
        walk: walk_impl_item_fn, walk_mut: walk_impl_item_fn_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            defaultness: leaf,
            sig => visit_signature / visit_signature_mut,
            body => visit_stmt_block / visit_stmt_block_mut,
        }
    }
    struct ImplItemConst {
        visit: visit_impl_item_const, visit_mut: visit_impl_item_const_mut,
        walk: walk_impl_item_const, walk_mut: walk_impl_item_const_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            defaultness: leaf,
            const_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            colon: skip,
            ty => visit_type / visit_type_mut,
            eq: skip,
            expr => visit_expr / visit_expr_mut,
            semi: skip,
        }
    }
    struct ImplItemType {
        visit: visit_impl_item_type, visit_mut: visit_impl_item_type_mut,
        walk: walk_impl_item_type, walk_mut: walk_impl_item_type_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            defaultness: leaf,
            type_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            eq: skip,
            ty => visit_type / visit_type_mut,
            semi: skip,
        }
    }
    struct ImplItemMacro {
        visit: visit_impl_item_macro, visit_mut: visit_impl_item_macro_mut,
        walk: walk_impl_item_macro, walk_mut: walk_impl_item_macro_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            mac => visit_macro_call / visit_macro_call_mut,
            semi: skip,
        }
    }
    enum TraitItem {
        visit: visit_trait_item, visit_mut: visit_trait_item_mut,
        walk: walk_trait_item, walk_mut: walk_trait_item_mut,
        variants {
            Fn(visit_trait_item_fn / visit_trait_item_fn_mut),
            Const(visit_trait_item_const / visit_trait_item_const_mut),
            Type(visit_trait_item_type / visit_trait_item_type_mut),
            Macro(visit_trait_item_macro / visit_trait_item_macro_mut),
        }
    }
    struct TraitItemFn {
        visit: visit_trait_item_fn, visit_mut: visit_trait_item_fn_mut,
        walk: walk_trait_item_fn, walk_mut: walk_trait_item_fn_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            sig => visit_signature / visit_signature_mut,
            default_body: opt => visit_stmt_block / visit_stmt_block_mut,
            semi: skip,
        }
    }
    struct TraitItemConst {
        visit: visit_trait_item_const, visit_mut: visit_trait_item_const_mut,
        walk: walk_trait_item_const, walk_mut: walk_trait_item_const_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            const_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            colon: skip,
            ty => visit_type / visit_type_mut,
            default: opt_pair => visit_expr / visit_expr_mut,
            semi: skip,
        }
    }
    struct TraitItemType {
        visit: visit_trait_item_type, visit_mut: visit_trait_item_type_mut,
        walk: walk_trait_item_type, walk_mut: walk_trait_item_type_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            type_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            colon: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
            default: opt_pair => visit_type / visit_type_mut,
            semi: skip,
        }
    }
    struct TraitItemMacro {
        visit: visit_trait_item_macro, visit_mut: visit_trait_item_macro_mut,
        walk: walk_trait_item_macro, walk_mut: walk_trait_item_macro_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            mac => visit_macro_call / visit_macro_call_mut,
            semi: skip,
        }
    }

    // ===== fields ========================================================
    enum Fields {
        visit: visit_fields, visit_mut: visit_fields_mut,
        walk: walk_fields, walk_mut: walk_fields_mut,
        variants {
            Named(visit_fields_named / visit_fields_named_mut),
            Unnamed(visit_fields_unnamed / visit_fields_unnamed_mut),
            Unit,
        }
    }
    struct FieldsNamed {
        visit: visit_fields_named, visit_mut: visit_fields_named_mut,
        walk: walk_fields_named, walk_mut: walk_fields_named_mut,
        fields {
            fields: seq_punct => visit_field_def / visit_field_def_mut,
        }
    }
    struct FieldsUnnamed {
        visit: visit_fields_unnamed, visit_mut: visit_fields_unnamed_mut,
        walk: walk_fields_unnamed, walk_mut: walk_fields_unnamed_mut,
        fields {
            fields: seq_punct => visit_field_def / visit_field_def_mut,
        }
    }
    struct Field {
        visit: visit_field_def, visit_mut: visit_field_def_mut,
        walk: walk_field_def, walk_mut: walk_field_def_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            vis => visit_visibility / visit_visibility_mut,
            mutability: leaf,
            ident: skip,
            colon: skip,
            ty => visit_type / visit_type_mut,
        }
    }
    struct FieldValue {
        visit: visit_field_value, visit_mut: visit_field_value_mut,
        walk: walk_field_value, walk_mut: walk_field_value_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            member: skip,
            colon_punct: skip,
            expr => visit_expr / visit_expr_mut,
            shorthand: skip,
        }
    }

    // ===== signatures ====================================================
    struct Signature {
        visit: visit_signature, visit_mut: visit_signature_mut,
        walk: walk_signature, walk_mut: walk_signature_mut,
        fields {
            constness: leaf,
            asyncness: leaf,
            unsafety: leaf,
            abi: skip,
            fn_keyword: skip,
            ident: skip,
            generics => visit_generics / visit_generics_mut,
            params: delim => visit_fn_params / visit_fn_params_mut,
            output => visit_return_type / visit_return_type_mut,
        }
    }
    struct FnParams {
        visit: visit_fn_params, visit_mut: visit_fn_params_mut,
        walk: walk_fn_params, walk_mut: walk_fn_params_mut,
        fields {
            inputs: punct => visit_fn_param / visit_fn_param_mut,
            variadic: opt => visit_variadic / visit_variadic_mut,
        }
    }
    enum FnParam {
        visit: visit_fn_param, visit_mut: visit_fn_param_mut,
        walk: walk_fn_param, walk_mut: walk_fn_param_mut,
        variants {
            Receiver(visit_receiver / visit_receiver_mut),
            Typed(visit_typed_param / visit_typed_param_mut),
        }
    }
    struct Receiver {
        visit: visit_receiver, visit_mut: visit_receiver_mut,
        walk: walk_receiver, walk_mut: walk_receiver_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            reference: skip,
            lifetime: skip,
            mutability: leaf,
            self_keyword: skip,
        }
    }
    struct BareFnArg {
        visit: visit_bare_fn_arg, visit_mut: visit_bare_fn_arg_mut,
        walk: walk_bare_fn_arg, walk_mut: walk_bare_fn_arg_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            name: skip,
            ty => visit_type / visit_type_mut,
        }
    }
    struct Variadic {
        visit: visit_variadic, visit_mut: visit_variadic_mut,
        walk: walk_variadic, walk_mut: walk_variadic_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            name: skip,
            dots: skip,
        }
    }

    // ===== generics ======================================================
    struct Generics {
        visit: visit_generics, visit_mut: visit_generics_mut,
        walk: walk_generics, walk_mut: walk_generics_mut,
        fields {
            lt_punct: skip,
            gt_punct: skip,
            params: punct => visit_generic_param / visit_generic_param_mut,
            where_clause: opt => visit_where_clause / visit_where_clause_mut,
        }
    }
    enum GenericParam {
        visit: visit_generic_param, visit_mut: visit_generic_param_mut,
        walk: walk_generic_param, walk_mut: walk_generic_param_mut,
        variants {
            Lifetime(visit_lifetime_param / visit_lifetime_param_mut),
            Type(visit_type_param / visit_type_param_mut),
            Const(visit_const_param / visit_const_param_mut),
        }
    }
    struct LifetimeParam {
        visit: visit_lifetime_param, visit_mut: visit_lifetime_param_mut,
        walk: walk_lifetime_param, walk_mut: walk_lifetime_param_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            lifetime: skip,
            colon_punct: skip,
            bounds: skip,
        }
    }
    struct TypeParam {
        visit: visit_type_param, visit_mut: visit_type_param_mut,
        walk: walk_type_param, walk_mut: walk_type_param_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            ident: skip,
            colon_punct: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
            eq_punct: skip,
            default: opt => visit_type / visit_type_mut,
        }
    }
    struct ConstParam {
        visit: visit_const_param, visit_mut: visit_const_param_mut,
        walk: walk_const_param, walk_mut: walk_const_param_mut,
        fields {
            attrs => visit_attributes / visit_attributes_mut,
            const_keyword: skip,
            ident: skip,
            colon_punct: skip,
            ty => visit_type / visit_type_mut,
            default_eq_punct: skip,
            default: opt => visit_expr / visit_expr_mut,
        }
    }
    struct WhereClause {
        visit: visit_where_clause, visit_mut: visit_where_clause_mut,
        walk: walk_where_clause, walk_mut: walk_where_clause_mut,
        fields {
            where_keyword: skip,
            predicates: punct => visit_where_predicate / visit_where_predicate_mut,
        }
    }
    enum WherePredicate {
        visit: visit_where_predicate, visit_mut: visit_where_predicate_mut,
        walk: walk_where_predicate, walk_mut: walk_where_predicate_mut,
        variants {
            Lifetime(visit_lifetime_predicate / visit_lifetime_predicate_mut),
            Type(visit_type_predicate / visit_type_predicate_mut),
        }
    }
    struct LifetimePredicate {
        visit: visit_lifetime_predicate, visit_mut: visit_lifetime_predicate_mut,
        walk: walk_lifetime_predicate, walk_mut: walk_lifetime_predicate_mut,
        fields {
            lifetime: skip,
            colon_punct: skip,
            bounds: skip,
        }
    }
    struct TypePredicate {
        visit: visit_type_predicate, visit_mut: visit_type_predicate_mut,
        walk: walk_type_predicate, walk_mut: walk_type_predicate_mut,
        fields {
            lifetimes: opt => visit_bound_lifetimes / visit_bound_lifetimes_mut,
            bounded_ty => visit_type / visit_type_mut,
            colon_punct: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
        }
    }
    enum TypeBound {
        visit: visit_type_bound, visit_mut: visit_type_bound_mut,
        walk: walk_type_bound, walk_mut: walk_type_bound_mut,
        variants {
            Trait(visit_trait_bound / visit_trait_bound_mut),
            Lifetime(skip),
            Use(visit_use_bound / visit_use_bound_mut),
        }
    }
    struct TraitBound {
        visit: visit_trait_bound, visit_mut: visit_trait_bound_mut,
        walk: walk_trait_bound, walk_mut: walk_trait_bound_mut,
        fields {
            polarity: skip,
            lifetimes: opt => visit_bound_lifetimes / visit_bound_lifetimes_mut,
            modifier: leaf,
            path => visit_path / visit_path_mut,
        }
    }
    struct TraitRef {
        visit: visit_trait_ref, visit_mut: visit_trait_ref_mut,
        walk: walk_trait_ref, walk_mut: walk_trait_ref_mut,
        fields {
            polarity: skip,
            path => visit_path / visit_path_mut,
        }
    }
    struct UseBound {
        visit: visit_use_bound, visit_mut: visit_use_bound_mut,
        walk: walk_use_bound, walk_mut: walk_use_bound_mut,
        fields {
            use_keyword: skip,
            lt_punct: skip,
            lifetimes: skip,
            gt_punct: skip,
        }
    }
    struct BoundLifetimes {
        visit: visit_bound_lifetimes, visit_mut: visit_bound_lifetimes_mut,
        walk: walk_bound_lifetimes, walk_mut: walk_bound_lifetimes_mut,
        fields {
            for_keyword: skip,
            lt: skip,
            params: skip,
            gt: skip,
        }
    }

    // ===== generic arguments =============================================
    struct AngleArguments {
        visit: visit_angle_arguments, visit_mut: visit_angle_arguments_mut,
        walk: walk_angle_arguments, walk_mut: walk_angle_arguments_mut,
        fields {
            lt_punct: skip,
            args: punct => visit_generic_argument / visit_generic_argument_mut,
            gt_punct: skip,
        }
    }
    struct ParenArguments {
        visit: visit_paren_arguments, visit_mut: visit_paren_arguments_mut,
        walk: walk_paren_arguments, walk_mut: walk_paren_arguments_mut,
        fields {
            params: seq_punct => visit_type / visit_type_mut,
            output => visit_return_type / visit_return_type_mut,
        }
    }
    enum GenericArgument {
        visit: visit_generic_argument, visit_mut: visit_generic_argument_mut,
        walk: walk_generic_argument, walk_mut: walk_generic_argument_mut,
        variants {
            Lifetime(skip),
            Type(visit_type / visit_type_mut),
            Const(visit_expr / visit_expr_mut),
            AssocType(visit_assoc_type_argument / visit_assoc_type_argument_mut),
            AssocConst(visit_assoc_const_argument / visit_assoc_const_argument_mut),
            Constraint(visit_constraint_argument / visit_constraint_argument_mut),
        }
    }
    struct AssocTypeArgument {
        visit: visit_assoc_type_argument, visit_mut: visit_assoc_type_argument_mut,
        walk: walk_assoc_type_argument, walk_mut: walk_assoc_type_argument_mut,
        fields {
            ident: skip,
            generics: opt => visit_angle_arguments / visit_angle_arguments_mut,
            eq_punct: skip,
            ty => visit_type / visit_type_mut,
        }
    }
    struct AssocConstArgument {
        visit: visit_assoc_const_argument, visit_mut: visit_assoc_const_argument_mut,
        walk: walk_assoc_const_argument, walk_mut: walk_assoc_const_argument_mut,
        fields {
            ident: skip,
            generics: opt => visit_angle_arguments / visit_angle_arguments_mut,
            eq_punct: skip,
            expr => visit_expr / visit_expr_mut,
        }
    }
    struct ConstraintArgument {
        visit: visit_constraint_argument, visit_mut: visit_constraint_argument_mut,
        walk: walk_constraint_argument, walk_mut: walk_constraint_argument_mut,
        fields {
            ident: skip,
            generics: opt => visit_angle_arguments / visit_angle_arguments_mut,
            colon_punct: skip,
            bounds: punct => visit_type_bound / visit_type_bound_mut,
        }
    }

    // ===== attributes ====================================================
    struct Attribute {
        visit: visit_attribute, visit_mut: visit_attribute_mut,
        walk: walk_attribute, walk_mut: walk_attribute_mut,
        fields {
            style: skip,
            meta: delim => visit_meta / visit_meta_mut,
        }
    }

    struct Meta {
        visit: visit_meta, visit_mut: visit_meta_mut,
        walk: walk_meta, walk_mut: walk_meta_mut,
        fields {
            path => visit_path / visit_path_mut,
            content => visit_meta_layout / visit_meta_layout_mut,
        }
    }

    enum MetaArgument {
        visit: visit_meta_argument, visit_mut: visit_meta_argument_mut,
        walk: walk_meta_argument, walk_mut: walk_meta_argument_mut,
        variants {
            Meta(visit_meta / visit_meta_mut),
            Value(visit_meta_value / visit_meta_value_mut),
        }
    }

    enum MetaLayout {
        visit: visit_meta_layout, visit_mut: visit_meta_layout_mut,
        walk: walk_meta_layout, walk_mut: walk_meta_layout_mut,
        variants {
            None,
            Alias {
                eq: skip,
                value: (visit_meta_value / visit_meta_value_mut),
            },
            List {
                items: punct => (visit_meta_argument / visit_meta_argument_mut),
            },
            Value(visit_meta_value / visit_meta_value_mut),
        }
    }

    enum MetaValue {
        visit: visit_meta_value, visit_mut: visit_meta_value_mut,
        walk: walk_meta_value, walk_mut: walk_meta_value_mut,
        variants {
            Literal(skip),
            Verbatim(skip),
        }
    }

    // ===== misc ==========================================================
    struct MacroCall {
        visit: visit_macro_call, visit_mut: visit_macro_call_mut,
        walk: walk_macro_call, walk_mut: walk_macro_call_mut,
        fields {
            path => visit_path / visit_path_mut,
            bang: skip,
            body: skip,
        }
    }
    struct PathSegment {
        visit: visit_path_segment, visit_mut: visit_path_segment_mut,
        walk: walk_path_segment, walk_mut: walk_path_segment_mut,
        fields {
            ident: skip,
            args => visit_path_arguments / visit_path_arguments_mut,
        }
    }
    enum PathArguments {
        visit: visit_path_arguments, visit_mut: visit_path_arguments_mut,
        walk: walk_path_arguments, walk_mut: walk_path_arguments_mut,
        variants {
            None,
            AngleBracketed(visit_angle_arguments / visit_angle_arguments_mut),
            Parenthesized(visit_paren_arguments / visit_paren_arguments_mut),
        }
    }

    // ===== use trees =====================================================
    enum UseTree {
        visit: visit_use_tree, visit_mut: visit_use_tree_mut,
        walk: walk_use_tree, walk_mut: walk_use_tree_mut,
        variants {
            Path(visit_use_path / visit_use_path_mut),
            Name(visit_use_name / visit_use_name_mut),
            Rename(visit_use_rename / visit_use_rename_mut),
            Glob(visit_use_glob / visit_use_glob_mut),
            Group(visit_use_group / visit_use_group_mut),
        }
    }
    struct UsePath {
        visit: visit_use_path, visit_mut: visit_use_path_mut,
        walk: walk_use_path, walk_mut: walk_use_path_mut,
        fields {
            ident: skip,
            path_sep: skip,
            tree: box => visit_use_tree / visit_use_tree_mut,
        }
    }
    struct UseName {
        visit: visit_use_name, visit_mut: visit_use_name_mut,
        walk: walk_use_name, walk_mut: walk_use_name_mut,
        fields {
            ident: skip,
        }
    }
    struct UseRename {
        visit: visit_use_rename, visit_mut: visit_use_rename_mut,
        walk: walk_use_rename, walk_mut: walk_use_rename_mut,
        fields {
            ident: skip,
            as_keyword: skip,
            rename: skip,
        }
    }
    struct UseGlob {
        visit: visit_use_glob, visit_mut: visit_use_glob_mut,
        walk: walk_use_glob, walk_mut: walk_use_glob_mut,
        fields {
            star: skip,
        }
    }
    struct UseGroup {
        visit: visit_use_group, visit_mut: visit_use_group_mut,
        walk: walk_use_group, walk_mut: walk_use_group_mut,
        fields {
            items: seq_punct => visit_use_tree / visit_use_tree_mut,
        }
    }

    // ===== irregular nodes (walkers hand-written below) ==================
    manual Attributes {
        visit: visit_attributes, visit_mut: visit_attributes_mut,
        walk: walk_attributes, walk_mut: walk_attributes_mut,
        manual {}
    }
    manual Path {
        visit: visit_path, visit_mut: visit_path_mut,
        walk: walk_path, walk_mut: walk_path_mut,
        manual {}
    }
    manual Stmt {
        visit: visit_stmt, visit_mut: visit_stmt_mut,
        walk: walk_stmt, walk_mut: walk_stmt_mut,
        manual {}
    }
    manual Visibility {
        visit: visit_visibility, visit_mut: visit_visibility_mut,
        walk: walk_visibility, walk_mut: walk_visibility_mut,
        manual {}
    }
    manual ReturnType {
        visit: visit_return_type, visit_mut: visit_return_type_mut,
        walk: walk_return_type, walk_mut: walk_return_type_mut,
        manual {}
    }
    manual ClosureParam {
        visit: visit_closure_param, visit_mut: visit_closure_param_mut,
        walk: walk_closure_param, walk_mut: walk_closure_param_mut,
        manual {}
    }
    manual ItemModContent {
        visit: visit_item_mod_content, visit_mut: visit_item_mod_content_mut,
        walk: walk_item_mod_content, walk_mut: walk_item_mod_content_mut,
        manual {}
    }
}

// ===== hand-written walkers for irregular nodes ==========================
// These nodes have shapes the macro spec can't express: private fields, tuple
// enum variants, struct-style enum variants, or `Option<tuple>` payloads.

/// `Attributes` is a newtype over `Vec<Attribute>` with a private field; walk it
/// via its `iter`/`iter_mut` accessors.
pub fn walk_attributes<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast Attributes) {
    for attr in node {
        v.visit_attribute(attr);
    }
}
pub fn walk_attributes_mut<V: VisitMut>(v: &mut V, node: &mut Attributes) {
    for attr in node {
        v.visit_attribute_mut(attr);
    }
}

/// `Path` has private fields but derefs to `Punctuated<PathSegment, _>`.
pub fn walk_path<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast Path) {
    for seg in node.iter() {
        v.visit_path_segment(seg);
    }
}
pub fn walk_path_mut<V: VisitMut>(v: &mut V, node: &mut Path) {
    for seg in node.iter_mut() {
        v.visit_path_segment_mut(seg);
    }
}

/// `Stmt` has tuple/box variants the enum spec can't express.
pub fn walk_stmt<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast Stmt) {
    match node {
        Stmt::Local(s) => v.visit_stmt_local(s),
        Stmt::Block(b) => v.visit_stmt_block(b),
        Stmt::Item(i) => v.visit_item(i),
        Stmt::Expr(e, _) => v.visit_expr(e),
        Stmt::Macro(m) => v.visit_stmt_macro(m),
    }
}
pub fn walk_stmt_mut<V: VisitMut>(v: &mut V, node: &mut Stmt) {
    match node {
        Stmt::Local(s) => v.visit_stmt_local_mut(s),
        Stmt::Block(b) => v.visit_stmt_block_mut(b),
        Stmt::Item(i) => v.visit_item_mut(i),
        Stmt::Expr(e, _) => v.visit_expr_mut(e),
        Stmt::Macro(m) => v.visit_stmt_macro_mut(m),
    }
}

/// `Visibility::Restricted` carries `Delimited<(In, Path)>`; only the path recurses.
pub fn walk_visibility<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast Visibility) {
    if let Visibility::Restricted { path, .. } = node {
        v.visit_path(&path.inner.1);
    }
}
pub fn walk_visibility_mut<V: VisitMut>(v: &mut V, node: &mut Visibility) {
    if let Visibility::Restricted { path, .. } = node {
        v.visit_path_mut(&mut path.inner.1);
    }
}

/// `ReturnType::Type(RArrow, Box<Type>)` is a tuple variant.
pub fn walk_return_type<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast ReturnType) {
    if let ReturnType::Type(_, ty) = node {
        v.visit_type(ty);
    }
}
pub fn walk_return_type_mut<V: VisitMut>(v: &mut V, node: &mut ReturnType) {
    if let ReturnType::Type(_, ty) = node {
        v.visit_type_mut(ty);
    }
}

/// `ClosureParam` is an enum with struct-style variants.
pub fn walk_closure_param<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast ClosureParam) {
    match node {
        ClosureParam::Typed { pat, ty, .. } => {
            v.visit_pattern(pat);
            v.visit_type(ty);
        }
        ClosureParam::Inferred { pat } => v.visit_pattern(pat),
    }
}
pub fn walk_closure_param_mut<V: VisitMut>(v: &mut V, node: &mut ClosureParam) {
    match node {
        ClosureParam::Typed { pat, ty, .. } => {
            v.visit_pattern_mut(pat);
            v.visit_type_mut(ty);
        }
        ClosureParam::Inferred { pat } => v.visit_pattern_mut(pat),
    }
}

/// `ItemMod::content` is `Option<Delimited<Vec<Item>>>`; iterate the inner items.
pub fn walk_item_mod_content<'ast, V: Visit<'ast>>(v: &mut V, node: &'ast Delimited<Vec<Item>>) {
    for item in &node.inner {
        v.visit_item(item);
    }
}
pub fn walk_item_mod_content_mut<V: VisitMut>(v: &mut V, node: &mut Delimited<Vec<Item>>) {
    for item in &mut node.inner {
        v.visit_item_mut(item);
    }
}
