Expression = ExpressionWithBlock | ExpressionWithoutBlock ;
ExpressionWithBlock = BlockExpression | AsyncBlockExpression | ConstBlockExpression | UnsafeBlockExpression | LoopExpression | IfExpression | IfLetExpression | MatchExpression | WhileExpression | WhileLetExpression | ForExpression ;
ExpressionWithoutBlock = LiteralExpression | PathExpression | TupleExpression | ArrayExpression | ArrayRepeatExpression | StructExpression | CallExpression | MethodCallExpression | FieldExpression | IndexExpression | AwaitExpression | TryExpression | UnaryExpression | RawBorrowExpression | BinaryExpression | AssignmentExpression | CompoundAssignmentExpression | RangeExpression | BorrowExpression | CastExpression | ClosureExpression | LetExpression | ReturnExpression | BreakExpression | ContinueExpression | MacroInvocation | ParenthesizedExpression ;
LiteralExpression = Literal ;
PathExpression = PathInExpression ;
ParenthesizedExpression = "(", InnerAttributes, Expression, ")" ;
TupleExpression = "(", InnerAttributes, [ Expression, { ",", Expression }, [ "," ] ], ")" ;
ArrayExpression = "[", InnerAttributes, [ Expression, { ",", Expression }, [ "," ] ], "]" ;
ArrayRepeatExpression = "[", Expression, ";", Expression, "]" ;
StructExpression = PathInExpression, "{", InnerAttributes, [ StructExpressionField, { ",", StructExpressionField }, [ "," ] ], [ "..", Expression ], "}" ;
StructExpressionField = Attributes, ( Identifier | IntegerLiteral ), [ ":", Expression ] ;
BlockExpression = "{", InnerAttributes, { Statement }, [ Expression ], "}" ;
AsyncBlockExpression = "async", [ "move" ], BlockExpression ;
ConstBlockExpression = "const", BlockExpression ;
UnsafeBlockExpression = "unsafe", BlockExpression ;
LoopExpression = [ LoopLabel, ":" ], "loop", BlockExpression ;
IfExpression = "if", Expression, BlockExpression, [ "else", ( BlockExpression | IfExpression | IfLetExpression ) ] ;
IfLetExpression = "if", LetExpression, { "&&", LetExpression | Expression }, BlockExpression, [ "else", ( BlockExpression | IfExpression | IfLetExpression ) ] ;
MatchExpression = "match", Expression, "{", InnerAttributes, { MatchArm }, "}" ;
MatchArm = Attributes, [ "|" ], Pattern, { "|", Pattern }, [ "if", Expression ], "=>", Expression, [ "," ] ;
WhileExpression = [ LoopLabel, ":" ], "while", Expression, BlockExpression ;
WhileLetExpression = [ LoopLabel, ":" ], "while", LetExpression, { "&&", LetExpression | Expression }, BlockExpression ;
ForExpression = [ LoopLabel, ":" ], "for", Pattern, "in", Expression, BlockExpression ;
LoopLabel = Lifetime ;
CallExpression = Expression, "(", [ Expression, { ",", Expression }, [ "," ] ], ")" ;
MethodCallExpression = Expression, ".", PathSegment, "(", [ Expression, { ",", Expression }, [ "," ] ], ")" ;
FieldExpression = Expression, ".", ( Identifier | IntegerLiteral ) ;
IndexExpression = Expression, "[", Expression, "]" ;
AwaitExpression = Expression, ".", "await" ;
TryExpression = Expression, "?" ;
UnaryExpression = ( "!" | "-" | "*" ), Expression ;
BorrowExpression = "&", [ "mut" ], Expression ;
RawBorrowExpression = "&", "raw", ( "const" | "mut" ), Expression ;
BinaryExpression = Expression, BinaryOperator, Expression ;
BinaryOperator = "+" | "-" | "*" | "/" | "%" | "^" | "&" | "|" | "<<" | ">>" | "&&" | "||" | "==" | "<" | ">" | "!=" | "<=" | ">=" ;
AssignmentExpression = Expression, "=", Expression ;
CompoundAssignmentExpression = Expression, CompoundAssignmentOperator, Expression ;
CompoundAssignmentOperator = "+=" | "-=" | "*=" | "/=" | "%=" | "^=" | "&=" | "|=" | "<<=" | ">>=" ;
RangeExpression = [ Expression ], ( ".." | "..=" ), [ Expression ] ;
CastExpression = Expression, "as", Type ;
ClosureExpression = [ ForLifetimes ], [ "async" ], [ "move" ], "|", [ ClosureParam, { ",", ClosureParam }, [ "," ] ], "|", [ "->", Type ], Expression ;
ClosureParam = Pattern, [ ":", Type ] ;
LetExpression = "let", Pattern, "=", Expression ;
ReturnExpression = "return", [ Expression ] ;
BreakExpression = "break", [ LoopLabel ], [ Expression ] ;
ContinueExpression = "continue", [ LoopLabel ] ;
