Generics = "<", [ GenericParam, { ",", GenericParam }, [ "," ] ], ">" ;
GenericParam = Attributes, ( LifetimeParam | TypeParam | ConstParam ) ;
LifetimeParam = Lifetime, [ ":", LifetimeBounds ] ;
TypeParam = Identifier, [ ":", TypeParamBounds ], [ "=", Type ] ;
ConstParam = "const", Identifier, ":", Type, [ "=", ConstParamDefault ] ;
ConstParamDefault = BlockExpression | Identifier | [ "-" ], LiteralExpression ;
ForLifetimes = "for", Generics ;
WhereClause = "where", [ WherePredicate, { ",", WherePredicate }, [ "," ] ] ;
WherePredicate = Lifetime, ":", LifetimeBounds | [ ForLifetimes ], Type, ":", TypeParamBounds ;
LifetimeBounds = Lifetime, { "+", Lifetime } ;
TypeParamBounds = TypeParamBound, { "+", TypeParamBound } ;
TypeParamBound = Lifetime | [ "?" ], [ ForLifetimes ], TraitBound | UseBound ;
TraitBound = PathInType, [ "(" , ")" ] ;
UseBound = "use", "<", UseBoundList, ">" ;
UseBoundList = ( Lifetime | Identifier ), { ",", ( Lifetime | Identifier ) }, [ "," ] ;
GenericArguments = AngleBracketedArguments | ParenthesizedArguments ;
AngleBracketedArguments = "<", [ GenericArgument, { ",", GenericArgument }, [ "," ] ], ">" ;
GenericArgument = Lifetime | Type | GenericBinding | GenericConstraint | GenericConst ;
GenericBinding = Identifier, "=", Type ;
GenericConstraint = Identifier, ":", TypeParamBounds ;
GenericConst = BlockExpression | [ "-" ], LiteralExpression | Identifier ;
ParenthesizedArguments = "(", [ Type, { ",", Type }, [ "," ] ], ")", [ "->", Type ] ;
