Module = InnerAttributes, { Item } ;
Item = Attributes, [ Visibility ], ( UseItem | ExternCrateItem | ModuleItem | ForeignModule | StaticItem | ConstItem | FunctionItem | TypeAlias | StructItem | Enumeration | Union | Trait | Implementation | MacroRulesDefinition | MacroInvocationSemi ) ;
UseItem = "use", UseTree, ";" ;
ExternCrateItem = "extern", "crate", ( Identifier | "self" ), [ "as", ( Identifier | "_" ) ], ";" ;
ModuleItem = [ "unsafe" ], "mod", Identifier, ( ";" | "{", Module, "}" ) ;
ForeignModule = [ "unsafe" ], "extern", [ Abi ], "{", InnerAttributes, { ForeignItem }, "}" ;
ForeignItem = Attributes, ( MacroInvocationSemi | [ Visibility ], ( "static", [ "mut" ], Identifier, ":", Type, ";" | ForeignFunction ) ) ;
ForeignFunction = [ Safety ], "fn", FunctionDeclaration, ";" ;
StaticItem = [ Safety ], "static", [ "mut" ], Identifier, ":", Type, "=", Expression, ";" ;
ConstItem = "const", ( Identifier | "_" ), ":", Type, "=", Expression, ";" ;
FunctionItem = FunctionQualifiers, "fn", FunctionDeclaration, BlockExpression ;
FunctionQualifiers = [ "const" ], [ "async" ], [ Safety ], [ "extern", [ Abi ] ] ;
Safety = "safe" | "unsafe" ;
FunctionDeclaration = Identifier, [ Generics ], "(", [ FunctionParam, { ",", FunctionParam }, [ "," ] ], ")", [ "->", Type ], [ WhereClause ] ;
FunctionParam = Attributes, ( "self" | "mut", "self" | "&", [ Lifetime ], [ "mut" ], "self" | Pattern, ":", Type ) ;
TypeAlias = "type", Identifier, [ Generics ], [ WhereClause ], "=", Type, ";" ;
StructItem = "struct", Identifier, [ Generics ], ( ";" | "(", [ TupleField, { ",", TupleField }, [ "," ] ], ")", [ WhereClause ], ";" | [ WhereClause ], "{", [ NamedField, { ",", NamedField }, [ "," ] ], "}" ) ;
Enumeration = "enum", Identifier, [ Generics ], [ WhereClause ], "{", [ EnumVariant, { ",", EnumVariant }, [ "," ] ], "}" ;
EnumVariant = Attributes, Identifier, [ "(", [ TupleField, { ",", TupleField }, [ "," ] ], ")" | "{", [ NamedField, { ",", NamedField }, [ "," ] ], "}" ], [ "=", Expression ] ;
Union = "union", Identifier, [ Generics ], [ WhereClause ], "{", [ NamedField, { ",", NamedField }, [ "," ] ], "}" ;
NamedField = Attributes, [ Visibility ], Identifier, ":", Type ;
TupleField = Attributes, [ Visibility ], Type ;
Trait = [ "unsafe" ], "trait", Identifier, [ Generics ], [ ":", TypeParamBounds ], [ WhereClause ], "{", InnerAttributes, { TraitAssociatedItem }, "}" ;
Implementation = [ "unsafe" ], "impl", [ Generics ], [ [ "!" ], PathInType, "for" ], Type, [ WhereClause ], "{", InnerAttributes, { ImplementationAssociatedItem }, "}" ;
TraitAssociatedItem = Attributes, ( TraitAssociatedConst | TraitAssociatedFunction | TraitAssociatedType | MacroInvocationSemi ) ;
TraitAssociatedConst = "const", Identifier, ":", Type, [ "=", Expression ], ";" ;
TraitAssociatedFunction = FunctionQualifiers, "fn", FunctionDeclaration, ( BlockExpression | ";" ) ;
TraitAssociatedType = "type", Identifier, [ Generics ], [ ":", TypeParamBounds ], [ WhereClause ], [ "=", Type ], ";" ;
ImplementationAssociatedItem = Attributes, ( ConstItem | FunctionItem | TypeAlias | MacroInvocationSemi ) ;
