Input = [ Shebang ], { Whitespace | Comment | Token } ;
Shebang = "#!", ? characters through the next line ending, except an inner attribute opener ? ;
Whitespace = ? one Rust whitespace character ? ;
Comment = LineComment | BlockComment ;
LineComment = "//", ? characters through the next line ending ? ;
BlockComment = "/*", { BlockComment | ? character other than an unmatched block-comment terminator ? }, "*/" ;
Identifier = NonKeywordIdentifier | RawIdentifier ;
NonKeywordIdentifier = IdentifierOrKeyword, ? excluding strict and reserved keywords ? ;
IdentifierOrKeyword = IdentifierStart, { IdentifierContinue } | "_", IdentifierContinue, { IdentifierContinue } ;
RawIdentifier = "r#", IdentifierOrKeyword, ? excluding crate, self, Self, and super ? ;
Lifetime = "'", ( Identifier | "_" ) ;
Literal = IntegerLiteral | FloatLiteral | CharLiteral | StringLiteral | RawStringLiteral | ByteLiteral | ByteStringLiteral | RawByteStringLiteral | CStringLiteral | RawCStringLiteral | BooleanLiteral ;
BooleanLiteral = "true" | "false" ;
IntegerLiteral = DecimalLiteral | BinaryLiteral | OctalLiteral | HexLiteral ;
DecimalLiteral = DecimalDigit, { DecimalDigit | "_" }, [ LiteralSuffix ] ;
BinaryLiteral = "0b", { "_" }, BinaryDigit, { BinaryDigit | "_" }, [ LiteralSuffix ] ;
OctalLiteral = "0o", { "_" }, OctalDigit, { OctalDigit | "_" }, [ LiteralSuffix ] ;
HexLiteral = "0x", { "_" }, HexDigit, { HexDigit | "_" }, [ LiteralSuffix ] ;
FloatLiteral = DecimalLiteral, ( ".", DecimalLiteral | [ ".", DecimalLiteral ], Exponent ), [ LiteralSuffix ] | DecimalLiteral, ".", ? not followed by '.', '_', or an identifier start ? ;
Exponent = ( "e" | "E" ), [ "+" | "-" ], { "_" }, DecimalDigit, { DecimalDigit | "_" } ;
CharLiteral = "'", Character, "'", [ LiteralSuffix ] ;
StringLiteral = "\"", { StringCharacter }, "\"", [ LiteralSuffix ] ;
RawStringLiteral = "r", RawStringBody, [ LiteralSuffix ] ;
ByteLiteral = "b'", ByteCharacter, "'", [ LiteralSuffix ] ;
ByteStringLiteral = "b\"", { ByteStringCharacter }, "\"", [ LiteralSuffix ] ;
RawByteStringLiteral = "br", RawStringBody, [ LiteralSuffix ] ;
CStringLiteral = "c\"", { CStringCharacter }, "\"", [ LiteralSuffix ] ;
RawCStringLiteral = "cr", RawStringBody, [ LiteralSuffix ] ;
RawStringBody = "\"", { RawStringCharacter }, "\"" | RawDelimiter, "\"", { RawStringCharacter }, "\"", RawDelimiter ;
RawDelimiter = "#", { "#" }, ? the same number of '#' tokens at both ends, at most 255 ? ;
LiteralSuffix = IdentifierOrKeyword ;
TokenTree = Token | DelimitedTokenTree ;
DelimitedTokenTree = "(", { TokenTree }, ")" | "[", { TokenTree }, "]" | "{", { TokenTree }, "}" ;
Token = IdentifierOrKeyword | RawIdentifier | CharLiteral | StringLiteral | RawStringLiteral | ByteLiteral | ByteStringLiteral | RawByteStringLiteral | CStringLiteral | RawCStringLiteral | FloatLiteral | IntegerLiteral | Lifetime | Punctuation | ReservedToken ;
Punctuation = "..." | "..=" | "<<=" | ">>=" | "!=" | "%=" | "&&" | "&=" | "*=" | "+=" | "-=" | "->" | ".." | "/=" | "::" | "<-" | "<<" | "<=" | "==" | "=>" | ">=" | ">>" | "^=" | "|=" | "||" | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "]" | "^" | "{" | "|" | "}" | "~" ;
ReservedToken = ? token sequence reserved by the Rust lexer ? ;
IdentifierStart = ? Unicode XID_Start ? ;
IdentifierContinue = ? Unicode XID_Continue ? ;
DecimalDigit = ? ASCII digit ? ;
BinaryDigit = "0" | "1" ;
OctalDigit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" ;
HexDigit = DecimalDigit | "a" | "b" | "c" | "d" | "e" | "f" | "A" | "B" | "C" | "D" | "E" | "F" ;
Character = ? valid Rust character literal body ? ;
StringCharacter = ? valid Rust string literal body ? ;
ByteCharacter = ? valid Rust byte literal body ? ;
ByteStringCharacter = ? valid Rust byte string literal body ? ;
CStringCharacter = ? valid Rust C string literal body excluding NUL ? ;
RawStringCharacter = ? valid Rust raw string literal body excluding CR and its closing delimiter ? ;
