Statement = Item | LetStatement | ExpressionStatement | ";" ;
LetStatement = Attributes, "let", Pattern, [ ":", Type ], [ "=", Expression, [ "else", BlockExpression ] ], ";" ;
ExpressionStatement = ExpressionWithBlock | ExpressionWithoutBlock, [ ";" ] ;
