[package]
name = "moxy-diagnostic"
description = "Rust macro diagnostics for moxy"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[build-dependencies]
moxy-build.workspace = true

[dependencies]
moxy-token.workspace = true
