[package]
name = "moxy-template"
description = "Rust quasi-quoting and token templating with explicit interpolation syntax and built-in template control flow"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
proc-macro = true
doctest = false

[lints]
workspace = true

[dependencies]
moxy-token.workspace = true
