name: Benchmark

on:
  push:
    branches: [master]
  schedule:
    # Run once per hour at the beginning of the hour (UTC)
    - cron: "0 * * * *"
  workflow_dispatch:
  workflow_call: {}

permissions:
  checks: write
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: bencherdev/bencher@main
      - name: Run benchmarks
        run: |
          bencher run \
          --project moxy \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ubuntu-latest \
          --adapter rust_criterion \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-upper-boundary 0.95 \
          cargo bench -p moxy
