name: Benchmark Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - benches/**
      - crates/**
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/bench_pull_request.yaml
      - .github/workflows/bench_pull_request_track.yaml
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: bencherdev/bencher@main
      - name: Run
        run: cargo bench -p moxy | tee output.txt
      - name: Upload Results
        uses: actions/upload-artifact@v7
        with:
          name: bench_results
          path: output.txt
      - name: Upload PR Event
        uses: actions/upload-artifact@v7
        with:
          name: pr_event
          path: ${{ github.event_path }}

  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - minimal
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Hyperfine
        run: cargo install hyperfine --version 1.20.0 --locked
      - name: moxy[${{ matrix.variant }}]
        run: |
          hyperfine \
            --export-json compile-moxy-${{ matrix.variant }}.json \
            --warmup 1 \
            'cargo build --manifest-path benches/compile/${{ matrix.variant }}/Cargo.toml --features moxy --release'
      - name: syn[${{ matrix.variant }}]
        run: |
          hyperfine \
            --export-json compile-syn-${{ matrix.variant }}.json \
            --warmup 1 \
            'cargo build --manifest-path benches/compile/${{ matrix.variant }}/Cargo.toml --features syn --release'
      - name: Upload Results
        uses: actions/upload-artifact@v7
        with:
          name: compile-results-${{ matrix.variant }}
          path: compile-*.json
